### ISSUE TITLE
Response callback never gets triggered

### ISSUE THREAD

**Issue by irwinmatt** [abdul-work/PaymentApp#1]
Hey, I'm working on the integration of our software with checout. I have this app loaded onto our device. When I try to run a payment it will go through the code and hit the Pay API call. It was my understanding that once a card is swiped after this API call, that the PaymentResponseListener Interface would trigger the Response function in the MainPage.xaml and that response argument would have the card info.
However when I swipe a test card the response callback is never triggered. Is there more I have to do to get the terminal to be functional?
(I have not modified this base code at all)

**Comment by irwinmatt** [comment]
Anyone around to address this issue?

**Comment by abdul-work** [comment]
I think your issue has been resolved after coordination with the team.
